# Fancy stats dictionary

fancy_stats <- function(dat){

  dat <- dat %>%
    mutate(term = recode(term,
                         "(Intercept)" = "Intercept",
                         "warmingWarming" = "W",
                         "warming" = "W",
                         ".grazing" = "C",
                         "origSiteID" = "S",
                         "origSiteIDSub-alpine" = "S",
                         "final_bio" = "B",
                         ".grazingNatural" = "G",
                         "Namount_kg_ha_y" = "N",
                         "poly(Namount_kg_ha_y, 2)1" = "N",
                         "poly(Namount_kg_ha_y, 2)2" = "N\U00B2",
                         "poly(Namount_kg_ha_y, 2)" = "N",
                         "warmingWarming:.grazing" = "WxC",
                         "warming:.grazing" = "WxC",
                         "warmingWarming:.grazingNatural" = "WxG",
                         "warmingWarming:Namount_kg_ha_y" = "WxN",
                         "warming:Namount_kg_ha_y" = "WxN",
                         "warmingWarming:poly(Namount_kg_ha_y, 2)1" = "WxN",
                         "warmingWarming:poly(Namount_kg_ha_y, 2)2" = "WxN\U00B2",
                         "warming:poly(Namount_kg_ha_y, 2)" = "WxN",
                         ".grazing:Namount_kg_ha_y" = "NxC",
                         ".grazingNatural:Namount_kg_ha_y" = "NxG",
                         ".grazing:poly(Namount_kg_ha_y, 2)1" = "NxC",
                         ".grazing:poly(Namount_kg_ha_y, 2)2" = "N\U00B2xC",
                         ".grazing:poly(Namount_kg_ha_y, 2)" = "NxC",
                         ".grazingNatural:poly(Namount_kg_ha_y, 2)1" = "NxG",
                         ".grazingNatural:poly(Namount_kg_ha_y, 2)2" = "N\U00B2xG",
                         "warmingWarming:.grazing:Namount_kg_ha_y" = "WxNxC",
                         "warming:.grazing:Namount_kg_ha_y" = "WxNxC",
                         "warmingWarming:.grazingNatural:Namount_kg_ha_y" = "WxNxG",
                         "warmingWarming:.grazing:poly(Namount_kg_ha_y, 2)1" = "WxNxC",
                         "warmingWarming:.grazing:poly(Namount_kg_ha_y, 2)2" = "WxN\U00B2xC",
                         "warmingWarming:.grazingNatural:poly(Namount_kg_ha_y, 2)1" = "WxNxG",
                         "warmingWarming:.grazingNatural:poly(Namount_kg_ha_y, 2)2" = "WxN\U00B2xG",
                         "warming:.grazing:poly(Namount_kg_ha_y, 2)" = "WxNxC",
                         "Residuals" = "Residuals",
                         "Nitrogen_log" = "N",
                         "warmingWarming:Nitrogen_log" = "WxN",
                         "warming:Nitrogen_log" = "WxN",
                         ".grazing:Nitrogen_log" = "NxC",
                         "warmingWarming:.grazing:Nitrogen_log" = "WxNxC",
                         "warming:.grazing:Nitrogen_log" = "WxNxC",
                         ".grazingNatural:Nitrogen_log" = "NxG",
                         "warmingWarming:.grazingNatural:Nitrogen_log" = "WxNxG"),
    # sort
    term = factor(term, levels = c("Intercept", "W", "N", "N\U00B2", "C", "G", "S", "B",
                                   "WxN", "WxN\U00B2", "WxC", "WxG", "NxC", "NxG", "N\U00B2xC", "N\U00B2xG",
                                   "WxNxC", "WxNxG", "WxN\U00B2xC", "WxN\U00B2xG", "Residuals")))
  return(dat)
}
