project:
  type: book
  output-dir: ../docs

book:
  title: "Global change impacts alpine grasslands throught the same mechanisms"
  chapters:
    - index.qmd
    - abstract.qmd
    - introduction.qmd
    - methods.qmd
    #- SEM_output.qmd

bibliography: bibliography.bib

csl: science-advances.csl

editor:
  markdown:
    wrap: sentence

execute:
  echo: false
  out-width: '100%'

format: html
#output-file: "ThreeD_paper.docx"
