---
editor: visual

bibliography: bibliography.bib
---

# Discussion

We found the expected net global change effects, that diversity decreases with warming and nitrogen and increases with grazing, which is in line with many other studies [@klein2004experimental; @kaarlejarvi2017herbivores; @wu2020additive; @shangguan2024plant; @anderson2025experimental; @Austrheim2001-nu; @klein2004experimental; @niedrist2009plant; @Bernes2015-yg; @post2023large]. Although, the magnitude and direct of the effect of the drivers was context dependent. <!-- Unsure what I need to say here: although context dependency in direction of warming effects (increase in subalpine), as well as magnitude of other effects and interactions. --> In this study, we take a step further by disentangling the direct and indirect effects of three global change drivers, to understand their underling mechanisms and to generalize across drivers and climate context. Specifically, we tested whether these global change drivers all operate on diversity indirectly, mediated through community biomass, which reflects the magnitude and type of competition. If that were true, knowing general patterns and trends in community biomass of plants could also predict changes in plant biodiversity rather than needing to understand all the direct effects of different drivers. 

We only found partial support for our hypothesis, with indirect effect through community biomass having substantial effects in the alpine community, but relatively little impact in the sub-alpine. At the sub-alpine site, warming and nitrogen addition affected diversity directly and even at the alpine site, we found strong direct effects of warming. Below, we explore community biomass-mediated effects on diversity in these experiments, the mechanisms underlying the direct effects of each of the global change drivers, why these mechanisms might differ between alpine and sub-alpine communities, and the implications for our ability to generalize impacts of global change factors.

### Community biomass-mediates effects of global change on diversity

The SEMs showed that all three global change drivers affect diversity indirectly through community biomass with an overall negative net effect, but only at the alpine site (@fig-cut-final-diversity). Nevertheless, the environmental affinities suggest that community biomass plays an important role even at the sub-alpine site. For both sites, we see a significant shift towards less light tolerant species with increasing community biomass, suggesting greater competition for light (REFs). A similar shift is evident in both sites for the warming and nitrogen addition treatments, which has been observed previously[@Klanderud2005-yx; @Wang2012-cj; @Fu2016-dw]. One possible explanation is that the sub-alpine site is less temperature and nutrient limited compared to the alpine site and also had fewer species to begin with, which could partly explain why we found much weaker indirect effects of the global change drivers via community biomass on diversity. The drivers had less impacted on community biomass (i.e. lower explanatory power in the regression model; @fig-1-biomass-diversity a), yielding a smaller range of biomass to manipulate. An alternative explanation of the lack of effect in the SEM is the likely non-linearity of the relationship between total plant biomass and the intensity of competition for light. In both sites, the biggest shift in the Ellenberg light indicator is at the highest levels of biomass or nitrogen <!-- I don't understand this -->

-   The alpine site is more co-limited by T and N, could this explain the pattern?

-   Warming and nitrogen addition indirectly decreased diversity and evenness, but not richness (Supplement Figure S5), suggesting a shift in abundance of species with different competitive abilities, rather than the loss of species.

Clipping and grazing effects on the diversity indices were always mediated through community biomass, except for a direct clipping effect on evenness at the sub-alpine. In line with many other studies, we found that clipping was able to prevent the loss of diversity and evenness under warming and nitrogen levels above 10 kg N ha^-1^ y^-1^ at the alpine site (@fig-1-biomass-diversity b), suggesting this was related to competitive release [@Austrheim2001-nu; @klein2004experimental; @niedrist2009plant; @Bernes2015-yg; @kaarlejarvi2017herbivores; @post2023large]. Interestingly, higher biomass and warming led to a shift to species with higher grazing tolerance in the alpine community. Previously, we have showed in the same experiment, that warming shifts the alpine community to more resources acquisitive traits @halbritter2025effects, which could mean that they grow faster and have a higher tolerance towards grazing. <!-- Although in the same paper we found that grazing in the alpine leads to more conservative traits, no interactions WxG -->

### Direct effects of global change on diversity

Warming had a direct positive effect on diversity, species richness, and evenness in the alpine community (@fig-cut-final-diversity), which likely reflects a shift in abundance of warm adapted species and colonization by species with a higher temperature requirements from the vegetation surrounding the transplanted community. This is supported by a strong shift in the temperature affinity with warming (@fig-toenails b). Contrary, at the sub-alpine site, warming had a strong negative direct effect on diversity and species richness, but without any accompanying shift in distribution of the temperature affinity. Interstingly, warming in the sub-alpine community also induced a shift towards more moisture demanding species, which was not observed in the alpine community. Overall, soil moisture decreased with warming at both sites (Supplement Figures 1 and 2, Supplement Table 1), however, in the last year of the experiment, warming had no effect and soil moisture rather increased at the boreal site (location of warmed sub-alpine communities; (Supplement Figure S1a). One possible explanation could be that warming at the alpine site shifted the community towards warm demanding species which are equally tolerant in moisture. However, at the sub-alpine site, the species were already highly temperature demanding, and with warming the less moisture tolerant species were lost. <!-- Something on dense biomass being more moist? -->

-   Using a similar SEM approach to study direct and indirect drivers of plant diversity in three temperate grasslands in Canada, @white2014direct also found that precipitation and clipping mediated species richness through shoot biomass, while warming had only direct negative effects. -\> where can this go?

Nitrogen addition had a direct negative effect on diversity at both sites, but the effect was much stronger and significant at the sub-alpine site. Nitrogen addition directly decreased evenness at the sub-alpine site, suggesting a shift in abundance rather than loss of species. This is unlikely due to a shift in nutrient demanding species since it only occurred in the alpine and was very small at the sub-alpine site. The environmental affinities however suggest that the strong direct effect of nitrogen addition is a consequence of acidification of fertilizing [@Kimmel2020-fo]. At both sites, there was a strong and significant shift towards more acid tolerant species with increasing nitrogen. The fertilization effect could have been stronger in the sub-alpine site, because it was less nutrient limited. In our study, this explanation is also supported by an increase in available calcium at high levels of nitrogen addition, which can be released from the bedrock under acid conditions \[*we have data from PRS probes to show that*\].

Clipping and grazing had no direct effects on diversity, except that clipping decreased evenness directly. The general pattern is reflected in that none of the environmental affinities showed any shifts due to clipping.

-   Grazing pressure very low at the alpine site, sub-alpine site has a long history of grazing

-   In the alpine warming and biomass increase grazing tolerance. But at sub-alpine site, clipping reduced biomass, but had no effect on diversity, suggesting that clipping was too low, to have an effect? Could that also explain the pattern in the sub-alpine?

-   Either these indicators measure the wrong thing for grazing, or ...?

The effect of clipping on diversity was always mediated through community biomass. Interestingly, we found that clipping was able to prevent the loss of diversity and evenness under warming and nitrogen levels above 10 kg N ha^-1^ y^-1^ at the alpine site (@fig-1-biomass-diversity b), suggesting this was related to competitive release [@Austrheim2001-nu; @klein2004experimental; @niedrist2009plant; @Bernes2015-yg; @kaarlejarvi2017herbivores; @post2023large]. Species loss was reduced at both clipping intensities, but only the intensive grazing treatment significantly increased diversity, suggesting that the medium grazing treatment was too low to effectively reduce competition for light in this community (i.e. less biomass reduction, @fig-1-biomass-diversity a). Clipping had no beneficial effect for biodiversity in the warmer and more productive sub-alpine community, despite reducing community biomass significantly, suggesting that the warmer sub-alpine community was too productive for our clipping treatments to effectively reduce competition.

Needed?

The natural grazing treatment had similar but less effect on diversity compared to clipping. Although, grazing reduced community biomass similarly to clipping, the grazing had a weaker effect mediated through community biomass on diversity (and also on the other diversity indices). We used clipping treatments to mimic grazing, which might bias the results, however, the difference between cutting and grazing are often minimal [@talle2016grazing]. Since the overall grazing effects were similar compared to clipping, it suggests that our simulated grazing treatment is comparable to natural grazing and that additional effects of grazing, such as different timing of biomass removal, trampling, and fertilization from the animals did not override the effect of biomass removal per se.

### Biomass and other stuff

Our main hypothesis was that the three global change drivers, warming, nitrogen addition, and clipping, operate through increased community biomass favoring more intense competition, especially for light, resulting in a decrease in vascular plant diversity. In line with the first part of this hypothesis, we found a strong increase in community biomass with warming and nitrogen addition in both alpine and sub-alpine communities, paralleling the findings of previous studies manipulating one or both of these drivers [@elmendorf2012plot; @Humbert2016-wg; @Zhang2023-xg]. Warming can increase biomass because of higher rates of photosynthesis, a longer growing season, or because higher microbial activity can increase nutrient availability, while nitrogen addition directly increases nutrient availability. The alpine site was strongly temperature and nutrient limited, resulting in a four to five times increase of community biomass with either warming or nitrogen addition. This co-limitation at the alpine site could be an explanation for the stronger mediation through biomass compared to the sub-alpine site. <!-- Last sentence, needs more explanation -->

-   Note that the warmed alpine and the unwarmed subalpine have very similar N slopes. They are living in the same climate! So even if the community is different, the N limitation is real at this temperature, but not colder (or warmer).

-   Biomass additive / compensatory effects of nitrogen and warming. The biomass of the warmed sub-alpine community did not increase above the maximum levels found at ambient climate, but reached the same biomass across the whole nitrogen gradient, indicating growth limited by other factors, possibly lower water availability at the warmer site(41), which might have been especially prominent due to a dry growing season in 2022 (Figure S1).

-   The major change in community biomass, diversity and evenness occurred at levels of nitrogen addition beyond 10 kg N ha\^-1\^ y^-1^, which is the critical load for significant changes in the structure and function of alpine and sub-alpine grasslands (35). This similar relationship between the warmed alpine and ambient sub-alpine communities suggests that colder alpine plant communities are not intrinsically less productive than those at lower elevation, but are limited by temperature-related environmental factors (27).

-   Interestingly, diversity indices based on change in abundance (i.e. evenness and diversity) showed more change in the cold alpine community in response to global change drivers, while indices based on change in species turnover (i.e. species richness and diversity), changed more in the warmer sub-alpine community. This might be because community changes in cold environments (i.e. the alpine) are often slow[(*45*)](https://paperpile.com/c/KKq9O1/ot2B) and changes in biomass (i.e. abundance) generally happen faster than species turnover (i.e. colonization or extinction) and there is often an extinction lag in alpine communities[(*14*, *15*, *46*)](https://paperpile.com/c/KKq9O1/ztDH+wbqE+5luD).

### Conclusions and implications

implications for our ability to generalize impacts of global change factors.

Our findings show that community biomass is a general indicator of mechanisms mediating global change impacts on plant diversity, in particular in colder and unproductive alpine grasslands. We found that several drivers including warming, nitrogen addition, clipping, and grazing work through the same mechanisms. However, at the same time, we also found that some drivers including warming and nitrogen addition operate through several mechanisms. \[*some implication, what does this mean: generally biomass works, but also direct effects are possible in particular in more productive systems?*\]. The relative importance of the drivers was not consistent across sites, advocates for replicating experiments across gradients and landscapes to allow more general understanding of ecological processes [@fraser2013coordinated; @prager2022integrating]. Our results showed that community proxies, such as environmental affinities can help to get a more general understanding of the underlying ecological processes.

\[*is this useful?*\] Our study was conducted over three years and thus looks at short-term responses, which can differ from long-term responses[(*56*, *57*)](https://paperpile.com/c/KKq9O1/egX7+3xXg). Long-term experiments across different climatic contexts are needed to understand where and how local adaptation of grazing regimes can be used as a tool to mitigate impacts of warming and pollution and inform adaptive management strategies that benefit biodiversity.

### Community biomass mediates global change impacts on diversity in alpine sites

Our main hypothesis was that the three global change drivers, warming, nitrogen addition, and clipping, operate through increased community biomass favoring more intense competition, especially for light, resulting in a decrease in vascular plant diversity. In line with the first part of this hypothesis, we found a strong increase in community biomass with warming and nitrogen addition in both alpine and sub-alpine communities, paralleling the findings of previous studies manipulating one or both of these drivers [@elmendorf2012plot; @Humbert2016-wg; @Zhang2023-xg]. Warming can increase biomass because of higher rates of photosynthesis, a longer growing season, or because higher microbial activity can increase nutrient availability, while nitrogen addition directly increases nutrient availability. The alpine site was strongly temperature and nutrient limited, resulting in a four to five times increase of community biomass with either warming or nitrogen addition. This co-limitation at the alpine site could be an explanation for the stronger mediation through biomass compared to the sub-alpine site. <!-- Last sentence, needs more explanation -->

While the effects of nitrogen addition and clipping were only indirectly, warming also directly increased Shannon diversity, at low levels of nitrogen addition (\< 25 kg N ha^-1^ y^-1^). An increase in diversity in response to warming is less common in warming experiments [@dainese2024global], but often observed over larger areas in historical observations [@steinbauer2018accelerated]. One alternative explanation for this direct warming effect could be species turnover through colonization or extinction unrelated to competitive interactions. Warming shifted the environmental affinities of the alpine community towards more shade tolerant, warmer and nutrient demanding species, supporting this idea. Since warming increased both species richness and evenness in the alpine community, this suggests that such species both colonized these communities and increased in abundance. Colonization is likely a more common mechanisms than extinctions, because it generally happen faster than extinctions and there is often an extinction lag in alpine communities [@Vandvik2020-hu; @Alexander2015-gu; @block2022ecological].

### Alternative mechanisms drive diversity shifts in the sub-alpine

The sub-alpine site was less temperature and nutrient limited compared to the alpine site and also had fewer species to begin with, which could partly explain why we found much weaker indirect effects of the global change drivers via community biomass on diversity. Warming and nitrogen addition had less impacted on community biomass (i.e. lower explanatory power in the regression model; @fig-1-biomass-diversity a), yielding a smaller range of biomass to manipulate.

Instead, we found stronger and negative direct effects of warming and nitrogen addition on diversit in the sub-alpine site. Warming also directly decreased species richness, while nitrogen addition decreased evenness, suggesting a loss of species due to warming, while nitrogen addition caused a shift in species abundance. Using a similar SEM approach to study direct and indirect drivers of plant diversity in three temperate grasslands in Canada, @white2014direct also found that precipitation and clipping mediated species richness through shoot biomass, while warming had only direct negative effects. The direct decrease in Shannon diversity and species richness with warming in our study, was therefore likely caused by the loss of light demanding species (i.e. shift in the distribution of light affinity; @fig-toenails)(REFs?). Surprisingly, warming and increased biomass also shifted the communities towards moister conditions. Experimental warming by transplanting is often associated with a decrease in soil moisture because of higher evapotranspiration (REF). We found that soil moisture in the warmed sub-alpine communities was slightly higher compared to the ambient communities (Supplement Figure S1a), suggesting that the increased biomass captured soil moisture. This wetting effect was however not consistent across years, and might have been an exception for that year.

An alternative explanation for direct negative effect of nitrogen is soil acidification [@Kimmel2020-fo]. The distributions of reaction affinity shifted indeed strongly towards lower values indicating a community with more acidic conditions. Nitrogen addition decreased both diversity and evenness (Supplementary Figure S5), suggesting an increase in abundance of species that tolerate more acidic conditions. In our study, this explanation is also supported by an increase in available calcium at high levels of nitrogen addition, which can be released from the bedrock under acid conditions \[*we have data from PRS probes to show that*\].

### Clipping affects diversity indirectly, but grazing effects are much weaker

The effect of clipping on diversity was always mediated through community biomass. Interestingly, we found that clipping was able to prevent the loss of diversity and evenness under warming and nitrogen levels above 10 kg N ha^-1^ y^-1^ at the alpine site (@fig-1-biomass-diversity b), suggesting this was related to competitive release [@Austrheim2001-nu; @klein2004experimental; @niedrist2009plant; @Bernes2015-yg; @kaarlejarvi2017herbivores; @post2023large]. Species loss was reduced at both clipping intensities, but only the intensive grazing treatment significantly increased diversity, suggesting that the medium grazing treatment was too low to effectively reduce competition for light in this community (i.e. less biomass reduction, @fig-1-biomass-diversity a). Clipping had no beneficial effect for biodiversity in the warmer and more productive sub-alpine community, despite reducing community biomass significantly, suggesting that the warmer sub-alpine community was too productive for our clipping treatments to effectively reduce competition.

The natural grazing treatment had similar but less effect on diversity compared to clipping. Although, grazing reduced community biomass similarly to clipping, the grazing had a weaker effect mediated through community biomass on diversity (and also on the other diversity indices). We used clipping treatments to mimic grazing, which might bias the results, however, the difference between cutting and grazing are often minimal [@talle2016grazing]. Since the overall grazing effects were similar compared to clipping, it suggests that our simulated grazing treatment is comparable to natural grazing and that additional effects of grazing, such as different timing of biomass removal, trampling, and fertilization from the animals did not override the effect of biomass removal per se.

Why weaker effect? Short-term study, other drivers are having negative effects (overriding grazing effect? additional species are available for colonisation...

**Some interesting points (unclear how to use these):**

-   Note that the warmed alpine and the unwarmed subalpine have very similar N slopes. They are living in the same climate! So even if the community is different, the N limitation is real at this temperature, but not colder (or warmer).

-   Biomass additive / compensatory effects of nitrogen and warming. The biomass of the warmed sub-alpine community did not increase above the maximum levels found at ambient climate, but reached the same biomass across the whole nitrogen gradient, indicating growth limited by other factors, possibly lower water availability at the warmer site(41), which might have been especially prominent due to a dry growing season in 2022 (Figure S1).

-   The major change in community biomass, diversity and evenness occurred at levels of nitrogen addition beyond 10 kg N ha\^-1\^ y^-1^, which is the critical load for significant changes in the structure and function of alpine and sub-alpine grasslands (35). This similar relationship between the warmed alpine and ambient sub-alpine communities suggests that colder alpine plant communities are not intrinsically less productive than those at lower elevation, but are limited by temperature-related environmental factors (27).

-   Interestingly, diversity indices based on change in abundance (i.e. evenness and diversity) showed more change in the cold alpine community in response to global change drivers, while indices based on change in species turnover (i.e. species richness and diversity), changed more in the warmer sub-alpine community. This might be because community changes in cold environments (i.e. the alpine) are often slow[(*45*)](https://paperpile.com/c/KKq9O1/ot2B) and changes in biomass (i.e. abundance) generally happen faster than species turnover (i.e. colonization or extinction) and there is often an extinction lag in alpine communities[(*14*, *15*, *46*)](https://paperpile.com/c/KKq9O1/ztDH+wbqE+5luD).

## Acknowledgements

We thank Sigurd Vikesland for sparking the idea for this experiment, and all the landowners for permission to use their land for this study. We thank Silje Östmann, Susanne Berthelsen, Linn Voldstad, Ingrid Dahle, Ragnhild Gya for helping with recording species composition, Dagmar Egelkraut and Linn Cecilie Krüger for experimental and site maintenance, and numerous students and friends including Elia Betschen, Leire Campos, Mary Chatzitriantafillou, Manon Denis, Mari Dybwad, Julie Eriksen, Joseph Gaudard, Regine Romain Goury, Gulbrandsen, Ragnhild Gya, Marie Hoensbroech, Jana Kovacic, Michaela Lebedova, Elisa Lehmann, Emma Little, Josh S. Lynn, Frida Merkesvik, Silvia Montagnani, Kevin Rechsteiner, Jana Rüthers, Christina Perez Sanchez, Christian Stømme, Eliska Suchoparova, Agnieszka Tokarczyk, Joachim Töpper, Alexander Vågenes, Camilla Zernichow, and Vincent Zimmermann for helping transplanting turfs and pretending to be grazers by clipping and then sorting plants. This study was supported by the Norwegian Research Council (Grant 287801).

## Competing interest

The authors declare that they have no competing interests.

## Data availability

All data underlying these analyses (including raw and processed data) are openly available on the Open Science Framework (OSF) repository[(63)](https://paperpile.com/c/KKq9O1/AhYc).

## Code availability

All code for downloading the data from the OSF repository, data transformation, analyses and producing this manuscript are available on GitHub[(64)](https://paperpile.com/c/KKq9O1/1ay0). The whole workflow is (hope-) fully reproducible by using a target pipeline[(65)](https://paperpile.com/c/KKq9O1/ZNBp) and a reproducible environment via renv[(66)](https://paperpile.com/c/KKq9O1/L148). Please fork the GitHub repo and reproduce the analyses and manuscript. Feedback on the efficiency, reproducibility and accuracy of the code and results are very welcome. The final version of the GitHub repository will be versioned on Zenodo.

## Author contributions

We follow the CreDiT taxonomy[(67)](https://paperpile.com/c/KKq9O1/38Gvd) and recognize the following author contributions, Conceptualization (co), Data curation (da), Formal analysis (fo), Funding acquisition (fu), Investigation (in), Methodology (me), Project administration (pr), Resources (re), Software (so), Supervision (su), Validation (va), Visualization (vi), Writing -- original draft (wo), and Writing -- review & editing (wr), as follows: AHH (co, da, fo, fu, in, me, pr, su, va, vi, wo, wr); DG (co, fu, me, wo, wr); KK (in, me, wr); RJT (fo, me, wr); GA (me, wr); JMA (me, wr); VV (co, fu, in, su, me, wo, wr).