---
editor: visual
theme: light

bibliography: bibliography.bib
---

```{r}
#| label: set-up-intro
#| echo: false
#| message: false
library(targets)
library(tarchetypes)

```

Aud H. Halbritter^1\*^, Deborah Goldberg^2^, Kari Klanderud^3^, Richard J. Telford^1^, Jake M. Alexander^4^, Gunnar Austrheim^5^, Vigdis Vandvik^1^

^1^ Department of Biological Sciences, University of Bergen, Bergen, Norway\
^2^ Department of Ecology and Evolutionary Biology, University of Michigan, Ann Arbor, MI, USA\
^3^ Faculty of Environmental Sciences and Natural Resource Management, Norwegian University of Life Sciences, Ås, Norway\
^4^ Institute of Integrative Biology, ETH Zürich, Zurich, Switzerland\
^5^ Department of Natural History, NTNU University Museum, Norwegian University of Science and Technology, Trondheim, Norway

\* Corresponding author: aud.halbritter\@uib.no

**Abstract**

Plant biodiversity is under pressure from multiple global change drivers including climate change, pollution, and land-use change. Theory suggests that several of these drivers affect plant biodiversity through their impacts on plant community biomass. We hypothesize that by using community biomass as a common currency, we can arrive at a more synthetic understanding of the direct and indirect effects of multiple global change drivers on plant diversity. We test this prediction in a replicated field experiment in alpine and sub-alpine grasslands, simulating the effects of three common global change drivers: climate warming (assessed via transplantation to lower elevation), atmospheric nitrogen deposition (N addition), and land-use change (natural grazing and clipping). We found that the three global change drivers affected community biomass and diversity, but the specific impact depended on the limiting resources at the site. As hypothesized, the three global change drivers operated indeed on diversity through community biomass, but only at the alpine site, where the grassland was both temperature and nutrient limited. Using environmental affinities to describe the change in environmental niches of the plant communities revealed that warming and nitrogen addition led to communities with higher competitive ability for nutrients and light. At the sub-alpine site, warming led to communities of less shade tolerant and more moisture demanding species, while high levels of nitrogen addition led to more acidic soils. Overall, our study showed that global change drivers operate through their impact on community biomass, providing a route to identifying limiting resources and synthesizing the mechanisms controlling plant biodiversity.

**Keywords:** adaptive management, biodiversity, climate change, productivity, land-use change, mountains, pollution

## Introduction

Anthropogenic global changes linked to land-use change, resource exploitation, climate change, invasive alien species, and pollution pose major and accelerating threats to biodiversity and ecosystem functioning [@Ipbes2019-sd]. These global change drivers do not act in isolation, but occur simultaneously and often interact in complex ways so that their cumulative impacts may exceed the sum of single drivers [@oliver2014interactions; @Komatsu2019-yr; @rillig2019role; @Speiser2022-st; @xue2024number]. Given these complexities, forecasting changes to biodiversity exposed to multiple global change drivers require an understanding of the mechanisms underlying the multifactorial nature of global change drivers.

A growing body of literature shows that single and multiple global change drivers affect community biomass, plant community composition and diversity in grasslands, assuming that the main underlying mechanisms for changes in diversity is competition for nutrients and light [@borer2014herbivores; @li2024water; @harpole2016addition; @klein2004experimental; @collins2022global], <!-- second part of sentence seems unclear --> with few exceptions where this specific mechanism has been tested [@eskelinen2022light; @hautier2009competition]. Warming and nitrogen addition typically increase community biomass (@fig-concept a), which can thus shift the intensity and nature of the dominant plant-plant interactions. Specifically, this may lead to communities with taller, faster growing species which are stronger competitors, especially for light [@Alexander2015-gu; @Vandvik2020-hu; @wust2021interaction]. Grazing removes biomass [@frank2005interactive; @Bernes2015-yg], while also adding nutrients from urine and dung, and so impacts on community biomass are variable but can lead to increased diversity, particularly in more productive habitats [@Austrheim2001-nu; @frank2005interactive; @niedrist2009plant; @Bernes2015-yg; @borer2024planning; @proulx1998reversal]. Thus, grazing has been shown to reverse the effects of warming and nitrogen addition preventing species loss [@kaarlejarvi2017herbivores; @klein2004experimental; @borer2014herbivores; @post2008opposing; @song2020grazing]. While most of these studies suggest that the global change impacts lead to a change in the magnitude of competition for resources, the mechanisms that different global change drivers are mediated through community biomass has rarely been tested in a unified way within a single experiment. @white2014direct studied direct and indirect effects of different drivers on plant diversity in three temperate grasslands and identified shoot biomass as a key indirect driver of species loss in response to grazing and precipitation. @Vandvik2020-hu showed that complex interactions of environmental drivers could be reduced by including biomass as a proxy of plant-plant interactions. We therefore propose that we could generalize the effects of multiple global change drivers by using community biomass as a *common currency*, which reflects the magnitude of their impacts on competitive interactions. If so, knowing the general patterns and trends in community biomass could predict changes in plant biodiversity without testing the direct effects of different global change drivers (@fig-concept).

<!-- is the idea here that you could say e.g. "with X and Y driver acting, biodiversity loss will be buffered because the effects of GCD trade-off; while with Y and Z loss will be enhanced"? Or maybe, the impacts of X and Y GCDs will be such and such in low fertility systems, but not in high. The latter obviously links directly to the "unexpected" results -->

![Two alternative hypotheses for how three global change drivers warming, nitrogen addition and clipping (or grazing) affect plant diversity. a) Warming, nitrogen deposition, and clipping (or grazing) affect diversity directly, or b) these drivers affect diversity indirectly, mediated through community biomass as a *common currency*.](figures/Figure1_hypotheses.png){#fig-concept width="600"}

We test this prediction with a global change experiment in mountain grasslands, because they harbor unique biodiversity and provide important ecosystem functions and services such as carbon sequestration, water cycling, and grazing pastures; underpinning the lives and livelihoods of hundreds of millions of people [@egan2017mountain]. We manipulate three common global change drivers in a field experiment: climate warming, nitrogen deposition, and clipping or natural grazing (@fig-methods).

Plant community responses to global change drivers often differ along environmental gradients and across habitats because effects can be direct or indirect and responses can be non-linear [@milchunas1993quantitative; @elmendorf2012plot; @Humbert2016-wg; @bjorkman2018plant; @delnevo2018plastic; @Vandvik2020-hu]. To assess the degree of context-dependency and how community responses are mediated through community biomass, we repeated the experiment in two different environments, an alpine and a sub-alpine grassland community in Western Norway. Montane grasslands in Norway are transhumance-based grazing systems [@reinton1955seter; @austad2004overview], grazed by domestic and natural grazers with the extant grazing pressure often decreasing with elevation [@halbritter2025effects]. The two sites represent different annual and growing season temperatures, with the alpine site being more temperature and nutrient limited (Supplementary Figures S1). By replicating the experiment in two different environmental contexts we can test the generality of our hypothesis [@fraser2013coordinated].

We hypothesize that these global change drivers affect diversity and species composition mediated through community biomass, resulting in a change in competitive interactions. Specifically, we expect warming and nitrogen addition to increase and clipping and grazing to decrease competitive interactions. Alternative mechanisms are also possible. For example, some species may be physiologically intolerant of very high or low temperature and therefore go locally extinct or successfully colonize, regardless of the competitive environment (REFs). Second, increased nitrogen addition, especially at high levels, can lead to acidic soil conditions [@tian2015global], which can lead to shifts in species composition and diversity due to differences in tolerance to acidic conditions, independently of competitive interactions. Similarly, some species may be particularly tolerant or intolerant to direct effects of grazing irrespective of competitive interactions [@archibald2019unified]. Such shifts in species composition might therefore not be mediated through community biomass. Ecological indicator values can be used to describe species community composition in response to environmental affinities and can provide further insights into the mechanisms of these dynamics [@diekmann2003species; @rumpf2018range].

Here we exposed montane grassland communities in Western Norway, replicated across an alpine and sub-alpine site, to three global change drivers (@fig-methods). Plant communities were transplanted to lower elevation to simulate warmer climate. We fertilized the communities using seven levels of nitrogen, ranging between 0 and 100 kg N ha^-1^ y^-1^, and simulated grazing by clipping at two different intensities and had one natural grazing treatment. After three years of global change treatments, we harvested community biomass at peak growing season and assessed the change in vascular plant species composition and diversity.