---
title: "Notes"
format: html
---

**Introductions**

Multiple global change drivers can cause complex interactions (Rillig et al., 2019; Speißer et al., 2022; Xue et al., 2024).

<https://www.nature.com/articles/s41467-022-35473-1>

<https://www.sciencedirect.com/science/article/pii/S0038071724001329?casa_token=B2CTafadCzoAAAAA:29RJrXySKjYqRJfWTWexvFui5MEytkfNZfFQGTFnLJeMYgiYCrJLHTWkNrmZBad3Ue-LBv98tA>

Zalandias (grwoth and survival) <https://nph.onlinelibrary.wiley.com/doi/full/10.1111/nph.17232>

Such synergistic global change effects pose a substantial threat to biodiversity and ecosystem functioning (Oliver et al., 2015; van der Plas, 2019; Xu et al., 2024).

SEM for direct and indirect effects of grazing/moving and fertilization on diversity (Socher): <https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.1365-2745.2012.02020.x>

SEM for abiotic factors and biomas and light on richness. Direct and indirect effects: <https://www.journals.uchicago.edu/doi/epdf/10.1086/285999>

SEM: climate and grazing, direct and indirect effects: <file:///Users/audhalbritter/Downloads/Ecol_95(11).pdf>

Ecologists should focus on fresh, mechanistic approaches to understanding the multivariate links between productivity and richness. And no relationship between biomass and richness. <https://www.science.org/doi/full/10.1126/science.1204498?casa_token=KAB3AvZQQOwAAAAA%3ATd94BJMoJq5uEaKhh_mRokAnuIDYAXzhQKPcNXqNpVOu8YNYQOETid8L4fgxauO_a4-cbmXBYi3O1w>

Grasslands: **Combatting global grassland degradation:** <https://www.nature.com/articles/s43017-021-00207-2>

Kaarlejärvi et al. 2017 multiple global change drivers: <https://www.nature.com/articles/s41467-017-00554-z#change-history>